wget -c ftp://www.ine.es/temas/epa/datos_1t05.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t05.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t05.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t05.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t06.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t06.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t06.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t06.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t07.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t07.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t07.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t07.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t08.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t08.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t08.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t08.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t09.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t09.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t09.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t09.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t10.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t10.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t10.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t10.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t11.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t11.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t11.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t11.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t12.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t12.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t12.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t12.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t13.zip
wget -c ftp://www.ine.es/temas/epa/datos_2t13.zip
wget -c ftp://www.ine.es/temas/epa/datos_3t13.zip
wget -c ftp://www.ine.es/temas/epa/datos_4t13.zip
wget -c ftp://www.ine.es/temas/epa/datos_1t14.zip
